<li class="dropdown <?php if ($page->isActive(true)) echo ' active' ?>">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
        <?php if ($page->get("icon") !== ""): ?>
            <span class="<?php echo $page->get("icon"); ?>"></span>
        <?php endif; ?>
        <?php echo $page->getLabel() ?>
        <span class="fa arrow"></span>

        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <?php foreach ($page->getPages() as $child): ?>
            <?php if (!$this->navigation()->accept($child)) continue; ?>
            <?php if ($child->get("separator") === true): ?>
                <li role="separator" class="divider"></li>
                    <?php
                    continue;
                endif;
                ?>
            <li<?php if ($child->isActive()) echo ' class="active"' ?>>
                <a 
                    href="<?php echo $child->getHref() ?>"
                    <?php if ($child->getTarget() != ""): ?>
                        target="<?php echo $child->getTarget(); ?>"
                    <?php endif; ?> >
                        <?php if ($child->get("icon") !== ""): ?>
                        <span class="<?php echo $child->get("icon"); ?>"></span>
                    <?php endif; ?>
                    <?php echo $child->getLabel() ?>
                </a>
            </li>
        <?php endforeach ?>
    </ul>
</li>  
