<!--MODAL-->
<div class="modal fade " id="<?php echo $this->modalId; ?>" data-backdrop="static" tabindex="-10" role="dialog" aria-labelledby="Properties">
    <div class="modal-dialog <?php echo $this->modalClass; ?>" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modalLabel"></h4>
            </div>
            <div class="modal-body" >
                <div class="modal-alerts">

                </div>
                <div class="modal-box">

                </div>

            </div>

        </div>
    </div>
</div>

<?php if ($this->modalJs): ?>
    <script type="text/javascript">
        var MetalModal;
        jQuery(function ($) {
            MetalModal = new $.MetalModal();
            MetalModal.run('<?php echo $this->modalId; ?>');
        });

    </script>
<?php endif; ?>


