<?php
/* @var $container Zend\Navigation\Navigation */
$container = $this->container;
?>
<ul class="<?php echo $this->navigation()->menu()->getUlClass(); ?>">
    <?php foreach ($container as $page): ?>
        <?php if (!$this->navigation()->accept($page)) continue; ?>
        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php if (!$hasChildren): ?>
            <?php echo $this->partial("zf-metal/commons/menu/horizontal/partial/li", array("page" => $page)); ?>
        <?php else: ?>
            <?php
            //check if access is allowed at least one item
            $access = false;
            foreach ($page->getPages() as $child) {
                if ($this->navigation()->accept($child) && $child->get("separator") !== true) {
                    $access = true;
                }
            } 
            ?>
    
            <?php if ($access) :?>
                    <?php echo $this->partial("zf-metal/commons/menu/horizontal/partial/dropdown", array("page" => $page)); ?>
            <?php endif; ?>
        <?php endif ?>
    <?php endforeach ?>
</ul>
