<?php
$form = $this->form;
$form->prepare();
$elementsReady = array();
?>

<?php echo $this->form()->openTag($form); ?>

<!--HORIZONTAL GROUPS-->
<?php if (count($this->horizontalGroups)): ?>
    <?php foreach ($this->horizontalGroups as $groupName => $group): ?>
        <div id="form-group-<?php echo $groupName; ?>">
            <legend><?php echo $groupName; ?></legend>
            <?php foreach ($group as $item): ?>
                <?php if ($form->has($item) && !in_array($item, $elementsReady)): ?>
                    <?php $element = $form->get($item); ?>
                    <?php $elementsReady[] = $item; ?>
                    <div class="<?php echo ($element->getAttribute('type') !== "hidden") ? $this->columnClass : "input-hidden"; ?>">
                        <?php echo $this->renderFormElement($element, $this->style); ?>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
        <div class="clearfix"></div>
    <?php endforeach; ?>

<?php endif; ?>

<!--VERTICAL-GROUPS-->
<?php if (count($this->verticalGroups)): ?>
    <?php foreach ($this->verticalGroups as $groupName => $group): ?>
        <div class="<?php echo $this->columnClass; ?>">

            <div id="form-group-<?php echo $groupName; ?>">
                <legend><?php echo $groupName; ?></legend>
                <?php foreach ($group as $item): ?>
                    <?php if ($form->has($item) && !in_array($item, $elementsReady)): ?>
                        <?php $element = $form->get($item); ?>
                        <?php $elementsReady[] = $item; ?>
                        <?php echo $this->renderFormElement($element, $this->style); ?>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endforeach; ?>

<?php endif; ?>        


<!--OTHERS-->
<?php foreach ($form as $element) : ?>
    <?php if (!in_array($element->getName(), $elementsReady) && $element->getAttribute('type') !== "submit" && $element->getAttribute('type') !== "button"): ?>
        <div class="<?php echo ($element->getAttribute('type') !== "hidden") ? $this->columnClass : "input-hidden"; ?>">
            <?php echo $this->renderFormElement($element, $this->style); ?>
        </div>

    <?php endif; ?>

<?php endforeach; ?>
<br>
<div class="clearfix"></div>
<br>

<!--SUBMIT & BUTTONS-->
<div class="col-lg-12 col-xs-12">
    <?php foreach ($form as $element) : ?>

        <?php if ($element->getAttribute('type') === "submit" || $element->getAttribute('type') === "button"): ?>
            <?php echo $this->renderFormElement($element, $this->style); ?>
        <?php endif; ?>

    <?php endforeach; ?>
</div>
<?php echo $this->form()->closeTag($form); ?>

