<?php
$form = $this->form;
$form->prepare();
$elementsReady = array();
?>

<?php echo $this->form()->openTag($form); ?>

<!--GROUPS-->
<?php if (count($this->groupsConfig)): ?>
    <?php foreach ($this->groupsConfig as $groupConfig): ?>
        <?php if ($groupConfig->getType() == \ZfMetal\Commons\Options\FormGroupConfig::TYPE_HORIZONTAL): ?>
            <!--HORIZONTAL-->
            <div class="clearfix"></div>
            <div id="form-group-<?php echo $groupConfig->getId(); ?>">

                <?php if ($groupConfig->getTitle()): ?>
                    <legend><?php echo $this->translate($groupConfig->getTitle()); ?></legend>
                <?php endif; ?>

                <?php foreach ($groupConfig->getFields() as $item): ?>
                    <?php if ($form->has($item) && !in_array($item, $elementsReady)): ?>
                        <?php $element = $form->get($item); ?>
                        <?php $elementsReady[] = $item; ?>
                        <div class="<?php echo ($element->getAttribute('type') !== "hidden") ? $groupConfig->getColumnClass() : "input-hidden"; ?>">
                            <?php echo $this->renderFormElement($element, $groupConfig->getStyle()); ?>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
            <div class="clearfix"></div>

        <?php endif; ?>

        <?php if ($groupConfig->getType() == \ZfMetal\Commons\Options\FormGroupConfig::TYPE_VERTICAL): ?>
            <!--VERTICAL-->
            <div class="<?php echo $this->columnClass; ?>">

                <div id="form-group-<?php echo $groupConfig->getId(); ?>">

                    <?php if ($groupConfig->getTitle()): ?>
                        <legend><?php echo $this->translate($groupConfig->getTitle()); ?></legend>
                    <?php endif; ?>

                    <?php foreach ($groupConfig->getFields() as $item): ?>
                        <?php if ($form->has($item) && !in_array($item, $elementsReady)): ?>
                            <?php $element = $form->get($item); ?>
                            <?php $elementsReady[] = $item; ?>
                            <?php echo $this->renderFormElement($element, $groupConfig->getStyle()); ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endif; ?>

    <?php endforeach; ?>
<?php endif; ?>

<!--OTHERS-->
<?php foreach ($form as $element) : ?>
    <?php if (!in_array($element->getName(), $elementsReady) && $element->getAttribute('type') !== "submit" && $element->getAttribute('type') !== "button"): ?>
        <div class="<?php echo ($element->getAttribute('type') !== "hidden") ? $this->columnClass : "input-hidden"; ?>">
            <?php echo $this->renderFormElement($element, $this->style); ?>
        </div>

    <?php endif; ?>

<?php endforeach; ?>
<br>
<div class="clearfix"></div>
<br>

<!--SUBMIT & BUTTONS-->
<div class="col-lg-12 col-xs-12">
    <?php foreach ($form as $element) : ?>

        <?php if ($element->getAttribute('type') === "submit" || $element->getAttribute('type') === "button"): ?>
            <?php echo $this->renderFormElement($element, $this->style); ?>
        <?php endif; ?>

    <?php endforeach; ?>
</div>
<?php echo $this->form()->closeTag($form); ?>

