<?php /* @var $groupConfig \ZfMetal\Commons\Options\FormGroupConfig */ ?>
<div class="<?php echo $groupConfig->getColumnClass(); ?>">

    <div id="form-group-<?php echo $groupConfig->getId(); ?>">
        
        <?php if ($groupConfig->getTitle()): ?>
            <legend><?php echo $this->translate($groupConfig->getTitle()); ?></legend>
        <?php endif; ?>
            
        <?php foreach ($groupConfig->getFields() as $item): ?>
            <?php if ($form->has($item) && !in_array($item, $elementsReady)): ?>
                <?php $element = $form->get($item); ?>
                <?php $elementsReady[] = $item; ?>
                <?php echo $this->renderFormElement($element, $groupConfig->getStyle()); ?>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</div>
