<div  class="form-group<?php if ($this->formElementErrors($this->element)) echo " has-error" ?>">
    <div class="checkbox col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <label>

            <?php echo $this->formElement($this->element); ?>
            <?php echo ucfirst($this->translate($this->element->getLabel())); ?>

        </label>


        <?php if ($element->getOption('description')): ?>
            <p class="help-block"><?php echo $this->element->getOption('description') ?></p>
        <?php endif; ?>

        <?php if ($this->formElementErrors($this->element)) : ?>
            <?php
            echo $this->formElementErrors()
                    ->setMessageOpenFormat('<span class="help-block">')
                    ->setMessageSeparatorString('</span><span class="help-block">')
                    ->setMessageCloseString('</span>')
                    ->render($this->element);
            ?>

        <?php endif; ?>

    </div>
</div>
