<?php
$class = $this->element->getAttribute("class");
if (!preg_match("/form-control/", $class)) {
    $this->element->setAttribute("class", $class . " form-control");
}
?>
<div  class="form-group<?php if ($this->formElementErrors($this->element)) echo " has-error" ?>">

    <label class="control-label"><?php echo ucfirst($this->translate($this->element->getLabel())); ?></label>

    <label class="btn btn-default glyphicon glyphicon-open">
        <?php echo $this->formFile($this->element); ?>
    </label>

    <?php if ($element->getOption('description')): ?>
        <p class="help-block"><?php echo $this->element->getOption('description') ?></p>
    <?php endif; ?>

    <?php if ($this->formElementErrors($this->element)) : ?>
        <?php
        echo $this->formElementErrors()
                ->setMessageOpenFormat('<span class="help-block">')
                ->setMessageSeparatorString('</span><span class="help-block">')
                ->setMessageCloseString('</span>')
                ->render($this->element);
        ?>

    <?php endif; ?>

</div>
